name:
on:
  push:
    branches: [ "main" ]
env:
  borgmatic_version: 1.9.2
  borg_version: 1.4.0
permissions:
  checks: write
  contents: write
  packages: write
  pull-requests: read
jobs:
  build-publish:
    name: Build and Publish
    runs-on: self-hosted
    strategy:
      matrix:
        postgres_version: [ "14", "15", "16" ]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
            registry.etke.cc/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable=${{ matrix.postgres_version == '' }}
            type=raw,value=${{ matrix.postgres_version }}-${{ env.borg_version }}-${{ env.borgmatic_version }},enable=${{ github.ref_name == 'main' }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            POSTGRES_VERSION=${{ matrix.postgres_version }}
            BORGMATIC_VERSION=${{ env.borgmatic_version }}
            BORG_VERSION=${{ env.borg_version }}
  build-publish-latest:
    name: Build and Publish (latest)
    runs-on: self-hosted
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
            registry.etke.cc/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            POSTGRES_VERSION=${{ matrix.postgres_version }}
            BORGMATIC_VERSION=${{ env.borgmatic_version }}
            BORG_VERSION=${{ env.borg_version }}
